### ISSUE TITLE
Jenkins questions

### ISSUE THREAD

**Issue by apoorvpandey-ap** [apoorvpandey-ap/test_jenkins#1]
- [x] 1. [What is the Architecture of Jenkins?](https://github.com/apoorvpandey-ap/test_jenkins/issues/1#issuecomment-1062517547)
- [x] 2. [Plugin of Jenkins](https://github.com/apoorvpandey-ap/test_jenkins/issues/1#issuecomment-1062751227)
- [x] 3. [Commands you can use to start Jenkins manually.](https://github.com/apoorvpandey-ap/test_jenkins/issues/1#issuecomment-1062800404)

**Comment by apoorvpandey-ap** [comment]
## Architecture
![image](https://user-images.githubusercontent.com/66588814/157366868-4feb3646-e0d8-4380-9f27-89f6530cea84.png)

**Comment by apoorvpandey-ap** [comment]
## Some Plugin of Jenkins
![image](https://user-images.githubusercontent.com/66588814/157418573-2518cedf-538d-4ca0-bec7-baa76e04b075.png)

**Comment by apoorvpandey-ap** [comment]
## Commands you can use to start Jenkins manually.
Start Jenkins: jenkins.exe start
Stop Jenkins: jenkins.exe stop
Restart Jenkins: jenkins.exe restart

**Comment by apoorvpandey-ap** [comment]
## Pipeline for Docker Image 
`pipeline { 

    environment { 

        registry = "apoorvvns/jenkins-test" 

        registryCredential = 'b3902a13-117c-4a8e-b76c-51c60f33cce7' 

       dockerImage = '' 

    }

    agent any 

    stages { 

        stage('Cloning our Git') { 

            steps { 

                git 'https://github.com/apoorvpandey-ap/Docker_1/' 

            }

        } 

        stage('Building our image') { 

            steps { 

                script { 

                    dockerImage = docker.build registry + ":$BUILD_NUMBER"

                }

            } 

        }

        stage('Deploy our image') { 

            steps { 

                script { 

                    docker.withRegistry( '', registryCredential ) {

                        dockerImage.push() 

                    }

                } 

            }

        } 

        stage('Cleaning up') { 

            steps { 

                sh "docker rmi $registry:$BUILD_NUMBER" 

            }

        } 

    }

}`

**Comment by apoorvpandey-ap** [comment]
![image](https://user-images.githubusercontent.com/66588814/165500910-f9dd3c0f-30ba-449b-9213-5eff23a860c6.png)
